# personal preferences
Metrics/LineLength:
  Max: 99

StringLiterals:
  EnforcedStyle: single_quotes

Style/AccessModifierIndentation:
  EnforcedStyle: outdent

Style/Documentation:
  Enabled: false

# gem specific configurations
Style/PredicateName:
  Enabled: false      # because this gem's name has the prefix `has_`
