AllCops:
  NewCops: enable
  TargetRubyVersion: 2.5

# personal preferences
Layout/LineLength:
  Max: 99

Style/Documentation:
  Enabled: false

# gem specific configurations
Naming/PredicateName:
  Enabled: false # because this gem's name has the prefix `has_`

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*_spec.rb' # because RSpec's DSL encourages lengthly blocks
