language: ruby
matrix:
  include:
    - rvm: 2.1.10
      gemfile: gemfiles/Gemfile.ruby-2.1.ci
    - rvm: 2.2.8
      gemfile: gemfiles/Gemfile.ruby-2.2.ci
    - rvm: 2.3.5
      gemfile: gemfiles/Gemfile.ruby-2.2.ci
    - rvm: 2.4.2
      gemfile: gemfiles/Gemfile.ruby-2.2.ci

script:
  - bundle exec rspec
  - bundle exec rubocop
